project:
  type: website

website:
  title: "Computational Cognitive Sciences Course - University of Luxembourg"

  sidebar:
    id: main
    title: "Computational Cognitive Sciences Course"
    align: center
    style: docked
    search: true
    pinned: true
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - "---"
      - section: "Lectures"
        contents: "lectures/**/index.qmd"
      - "---"
      - section: "Resources"
        contents:
          - text: Useful Links
            icon: link-45deg
            href: links.qmd
          - icon: github
            text: GitHub
            href: https://github.com/ccs-unilu
          - text: Zotero
            icon: bookmarks
            href: https://www.zotero.org/groups/5774007/ccs-unilu/library
          - text: Moodle (2025)
            icon: person-video3
            href: https://moodle.uni.lu/course/view.php?id=8159
          - text: Moodle (2026)
            icon: person-video3
            href: https://moodle.uni.lu/course/view.php?id=8492

format:
  html:
    # theme: cosmo
    css: assets/css/styles.css
    link-external-icon: true
    link-external-newwindow: true
