project:
  type: website

website:
  title: "CompCogSci @ Uni.lu"

  sidebar:
    align: center
    style: docked
    search: true
    pinned: true
    collapse-level: 2
    contents:
      - text: Home
        href: index.qmd
      - section: "2026"
        contents: "2026/*.qmd"
      - text: "2025"
        href: 2025/topics.qmd
      - "---"
      - text: Zotero
        icon: bookmarks
        href: https://www.zotero.org/groups/5774007/ccs-unilu/library
      - text: Moodle (2025)
        icon: person-video3
        href: https://moodle.uni.lu/course/view.php?id=8159
      - text: Moodle (2026)
        icon: person-video3
        href: https://moodle.uni.lu/course/view.php?id=8492
      - icon: github
        text: GitHub
        href: https://github.com/ccs-unilu
      - href: about.qmd
        icon: info-circle
format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    link-external-icon: true
    link-external-newwindow: true
